### ISSUE TITLE
Newrelic-logs-salesforce-eventlogfile (413 Error)

### ISSUE THREAD

**Issue by mattkimballut** [newrelic-experimental/newrelic-logs-salesforce-eventlogfile#1]
We are currently attempting to set up and use the " [newrelic-logs-salesforce-eventlogfile](https://github.com/newrelic-experimental/newrelic-logs-salesforce-eventlogfile)" experimental integration. We are able to authenticate and run the script just fine, but are receiving the following error from the New Relic log API:

“newrelic logs api returned code- 413”

It appears that no data is being ingested by NR.

python src/main.py
using program arguments []

Running query SELECT+Id,+EventType,+CreatedDate,+LogDate,+Interval,+LogFile,+Sequence+From+EventLogFile+Where+LogDate>=2022-04-28T12:20:28.395Z+AND+LogDate<2022-04-28T13:20:29.111Z+AND+Interval=‘Hourly’

sent 1555 log messages from log file ApexCallout/0AT3c000003qOzoGAE

sent 14279 log messages from log file ApexExecution/0AT3c000003qOzpGAE

sent 6283 log messages from log file ApexRestApi/0AT3c000003qOzqGAE

sent 829 log messages from log file ApexSoap/0AT3c000003qOzrGAE

sent 12861 log messages from log file ApexTrigger/0AT3c000003qOzsGAE

sent 10102 log messages from log file API/0AT3c000003qOztGAE

sent 167 log messages from log file ApiTotalUsage/0AT3c000003qOzuGAE

sent 302 log messages from log file AsyncReportRun/0AT3c000003qOzvGAE

newrelic logs api returned code- 413

sent 5 log messages from log file Console/0AT3c000003qOzxGAE

sent 64 log messages from log file ContentDocumentLink/0AT3c000003qOzyGAE

sent 205 log messages from log file ContentTransfer/0AT3c000003qOzzGAE

sent 301 log messages from log file Dashboard/0AT3c000003qP00GAE

sent 819 log messages from log file DocumentAttachmentDownloads/0AT3c000003qP01GAE

sent 6403 log messages from log file FlowExecution/0AT3c000003qP02GAE

sent 1 log messages from log file LightningError/0AT3c000003qP03GAE

newrelic logs api returned code- 413

sent 2212 log messages from log file LightningPageView/0AT3c000003qP05GAE

sent 30787 log messages from log file LightningPerformance/0AT3c000003qP06GAE

sent 5 log messages from log file LoginAs/0AT3c000003qP07GAE

sent 449 log messages from log file Login/0AT3c000003qP08GAE

sent 242 log messages from log file Logout/0AT3c000003qP09GAE

sent 1 log messages from log file NamedCredential/0AT3c000003qP0AGAU

sent 132 log messages from log file OneCommerceUsage/0AT3c000003qP0BGAU

sent 899 log messages from log file QueuedExecution/0AT3c000003qP0CGAU

sent 211 log messages from log file Report/0AT3c000003qP0DGAU

sent 8 log messages from log file ReportExport/0AT3c000003qP0EGAU

sent 1158 log messages from log file RestApi/0AT3c000003qP0FGAU

sent 122 log messages from log file SearchClick/0AT3c000003qP0GGAU

sent 2804 log messages from log file Search/0AT3c000003qP0HGAU

sent 1120 log messages from log file Sites/0AT3c000003qP0IGAU

sent 13673 log messages from log file PlatformEncryption/0AT3c000003qP0JGAU

sent 124 log messages from log file TimeBasedWorkflow/0AT3c000003qP0KGAU

newrelic logs api returned code- 413

sent 3943 log messages from log file VisualforceRequest/0AT3c000003qP0MGAU

any ideas?

**Comment by shahramk** [comment]
one possibility is that the data is older than 24 hours, and is not ingested. 
if you share your config.yml file, it'd help pinpoint the issue.

**Comment by mattkimballut** [comment]
Of course. Please see below. I have obfuscated the authentication and account info for security purposes. Thanks for the help!

integration_name: com.newrelic.labs.sfdc.eventlogfiles
run_as_service: False
cron_interval_minutes: 15
service_schedule: { "hour":  "*", "minute": "30" }
instances:
  - name: sfdc-logs
    arguments:
      token_url: "https://login.salesforce.com/services/oauth2/token"
      auth: {
        "grant_type": "password",
        "client_id": "xxx",
        "client_secret": "xxx",
        "username": "xxx",
        "password": "xxx"
      }
      cache_enabled: False
      redis: {
        "host": "",
        "port": "",
        "db_number": 0,
        "password": ""
      }
      date_field: "LogDate"
      generation_interval: "Hourly"
      time_lag_minutes: 300
    labels:
      environment: production
newrelic:
  data_format: "logs"
  api_endpoint: "US"
  account_id: "2108892"
  license_key: "xxx"

**Comment by mattkimballut** [comment]
[config.yml.txt](https://github.com/newrelic-experimental/newrelic-logs-salesforce-eventlogfile/files/8586093/config.yml.txt)

**Comment by shahramk** [comment]
actually error 413 mean the payload is too large. you might need to clear the existing logs from salesforce account, and start fresh.

**Comment by shahramk** [comment]
Hi @mattkimballut 

I am closing this issue. If it is still an existing problem, please update this issue with a comment and details. I'd be happy to help further with it.
